# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03a9180f2583b5ea0b4ed6b3dcd0afe7f9a1feb665d9e60c98050ad2f4649a0a841d2f300302c30a919b1f6d79749636efafc57dde2775dc80d0b7940149a476

test:
  secret_key_base: 06aabb220ae7f0e68d22669b19b2dd51c4fd7acaf8944d6a69b1d0c4b16630e4b953aa2dc72eee26c660210988f4e59500aee9084b244ad156212197b9138047

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
